### ISSUE TITLE
Broken console message

### ISSUE THREAD

**Issue by arshadkazmi42** [gh-conf/upfork#6]
Check mark and Branch synced message should be on the same line without any line breaks

<img width="630" alt="Screen Shot 2019-11-09 at 7 07 22 PM" src="https://user-images.githubusercontent.com/4654382/68529400-5b148980-0324-11ea-93fc-24eb50c8c8be.png">

**Comment by theashraf** [comment]
Can I work on this?

**Comment by arshadkazmi42** [comment]
Yes please. Go ahead.
